In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.13.1'

* Construct a graph
* Run

In [3]:
matrix = tf.zeros((3,4))

In [4]:
matrix

<tf.Tensor 'zeros:0' shape=(3, 4) dtype=float32>

In [5]:
tf.reshape(matrix,(2,6))

<tf.Tensor 'Reshape:0' shape=(2, 6) dtype=float32>

## constant operations

In [7]:
a = tf.constant(2,name='a')
b = tf.constant(3,name='b')
x = tf.add(a,b)
with tf.Session() as sess:
    writer = tf.summary.FileWriter('log/graphs/const_add',sess.graph)
    print(sess.run(x))
writer.close()

5


* tf.zeros ones zeros_like ones_like fill constant    
* tf.linspace range

Operations: div mod ...    
datatype: tf.float32 tf.float64 tf.int8 16...64 tf.string tf.bool

In [19]:
a1 = tf.zeros_like(a,optimize=True)

In [11]:
!tensorboard --logdir='./log/graphs/const_add' --port=1234

W0625 16:30:14.479759 140666813912832 plugin_event_accumulator.py:294] Found more than one graph event per run, or there was a metagraph containing a graph_def, as well as one or more graph events.  Overwriting the graph with the newest event.
TensorBoard 1.13.1 at http://nick-TM1705:1234 (Press CTRL+C to quit)
^C


In [13]:
a = tf.constant([2,2],name='vec_a')
b = tf.constant([[0,1],[2,3]],name='vec_b')
x = tf.multiply(a,b,name='dot_product')
with tf.Session() as sess:
    writer = tf.summary.FileWriter('log/graphs/const_mul',sess.graph)
    print(sess.run(x))
writer.close()

[[0 2]
 [4 6]]


In [14]:
a = tf.constant([[2,2],[1,4]],name='mat_a')
b = tf.constant([[0,1],[2,3]],name='mat_b')
y = tf.matmul(a,b,name='mat_product')
with tf.Session() as sess:
    writer = tf.summary.FileWriter('log/graphs/const_mul_2',sess.graph)
    print(sess.run(y))
writer.close()

[[ 4  8]
 [ 8 13]]


tf.Session.run(fetches,feed_dict,options,run_metadata)    
fetches:[x,y]

In [18]:
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0],name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0],name='b')
    c = tf.multiply(a,b)
    
    writer = tf.summary.FileWriter('log/graphs/const_mul_gpu',sess.graph)
    sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
    print(sess.run(c))
writer.close()

[ 1.  4.  9. 16. 25. 36.]


## variables

In [20]:
a = tf.Variable(2,name='scalar')
b = tf.Variable([2,3],name='vector')
c = tf.Variable([[1,2],[2,3]],name='matrix')

Instructions for updating:
Colocations handled automatically by placer.


In [21]:
a.initializer

<tf.Operation 'scalar/Assign' type=Assign>

In [22]:
a.value()

<tf.Tensor 'scalar/read:0' shape=() dtype=int32>

In [25]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)

In [27]:
init_ab = tf.variables_initializer([a,b],name='init_ab')
with tf.Session() as sess:
    sess.run(init_ab)

In [36]:
W = tf.Variable(tf.zeros((2,3)))
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W)
    print(W.eval())

<tf.Variable 'Variable_2:0' shape=(2, 3) dtype=float32_ref>
[[0. 0. 0.]
 [0. 0. 0.]]


* placeholder 用於存放訓練數據

In [37]:
a = tf.placeholder(tf.float32,shape=[3])
b = tf.constant([5,5,5],tf.float32)
c = tf.add(a,b)

with tf.Session() as sess:
    print(sess.run(c,feed_dict={a:[1,2,3]}))

[6. 7. 8.]
